// src/app/login/page.tsx
'use client'

import Link from "next/link";
import { realizarLogin } from "./login-actions";
import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const [state, formAction] = useActionState(realizarLogin, { message: "", sucess: false });
  const router = useRouter();

  useEffect(() => {
    if (state.sucess) {
      router.push('/dashboard');
    }
  }, [state.sucess, state.user, router]);

  return (
    <section
      className="min-h-screen w-full flex items-center justify-center"
      style={{ background: "linear-gradient(135deg, #0f172a 0%, #1a2e1a 50%, #0f2a0f 100%)" }}
    >
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute -top-32 -left-32 w-96 h-96 rounded-full opacity-20" style={{ background: "radial-gradient(circle, #22c55e, transparent 70%)" }} />
        <div className="absolute -bottom-32 -right-32 w-96 h-96 rounded-full opacity-15" style={{ background: "radial-gradient(circle, #16a34a, transparent 70%)" }} />
      </div>

      <div className="relative flex flex-col items-center px-4 w-full max-w-[440px]">
        <Link href="#" className="flex items-center mb-8 gap-2">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: "linear-gradient(135deg, #22c55e, #16a34a)" }}>
            <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <span className="text-2xl font-bold text-white tracking-tight">Fiscalize <span className="text-primary-400">Finanças</span></span>
        </Link>

        <div
          className="w-full rounded-2xl p-8 shadow-2xl"
          style={{ background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", backdropFilter: "blur(20px)" }}
        >
          <h1 className="text-2xl font-bold text-white mb-3">Bem-vindo de volta</h1>
          <p className="text-sm font-bold text-white mb-7">Entre na sua conta para continuar</p>

          <form className="space-y-5" action={formAction}>
            {!state.sucess && state.message.length > 0 && (
              <div className="flex items-center gap-2 bg-red-500/20 border border-red-500/40 text-red-300 text-sm font-medium rounded-xl px-4 py-3">
                <svg className="w-4 h-4 shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" /></svg>
                {state.message}
              </div>
            )}

            <div className="space-y-1.5">
              <label htmlFor="email" className="block text-sm font-medium text-white">E-mail</label>
              <input
                type="email" name="email" id="email"
                placeholder="email@exemplo.com"
                required
                className="w-full px-4 py-3 rounded-xl text-white placeholder-gray-500 text-sm outline-none transition-all focus:ring-2 focus:ring-primary-500"
                style={{ background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.12)" }}
              />
            </div>

            <div className="space-y-1.5">
              <label htmlFor="password" className="block text-sm font-medium text-white">Senha</label>
              <input
                type="password" name="password" id="password"
                placeholder="••••••••"
                required
                className="w-full px-4 py-3 rounded-xl text-white placeholder-gray-500 text-sm outline-none transition-all focus:ring-2 focus:ring-primary-500"
                style={{ background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.12)" }}
              />
            </div>

            <div className="text-right">
              <Link href="/reset-password" className="text-sm text-primary-400 hover:text-primary-300 transition-colors">
                Esqueci a senha
              </Link>
            </div>

            <button
              type="submit"
              className="w-full py-3 px-5 rounded-xl font-bold text-white text-sm transition-all hover:opacity-90 hover:scale-[1.01] active:scale-[0.99] shadow-lg"
              style={{ background: "linear-gradient(135deg, #22c55e, #16a34a)", boxShadow: "0 4px 24px rgba(34,197,94,0.3)" }}
            >
              Entrar
            </button>

            <p className="text-sm text-gray-400 text-center pt-1">
              Novo por aqui?{" "}
              <Link href="/register" className="font-semibold text-primary-400 hover:text-primary-300 transition-colors">
                Criar conta
              </Link>
            </p>
          </form>
        </div>
      </div>
    </section>
  );
}

// src/app/views/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CookieService } from '../../service/cookie.service';
import { LocalStorageService } from '../../service/localStorage.service';


import { LoginService } from '../../service/login.service';
import { LoginInterface } from '../../interface/login';

@Component({
  selector: 'app-login',
  imports: [FormsModule, ReactiveFormsModule, CommonModule, RouterModule],
  standalone: true,
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})

export class LoginComponent implements OnInit {
  erroLogin: string = '';
  formLogin: FormGroup = new FormGroup({});
  manterLogin: boolean = false;
  carregando: boolean = false;

  constructor(
    private fb: FormBuilder,
    private cookieService: CookieService,
    private localStorage: LocalStorageService,
    private router: Router,
    private loginService: LoginService
  ) { }

  ngOnInit(): void {
    this.inicializaForm()
  }

  inicializaForm() {
    this.manterLogin = this.localStorage.getStorage('manterLogin') || false;
    this.formLogin = this.fb.group({
      email: ['', [Validators.required, Validators.email, Validators.maxLength(24)]],
      senha: ['', [Validators.required, Validators.minLength(6), Validators.maxLength(24)]],
      manterLogin: [this.manterLogin]
    });
  }

  salvaLogin() {
    this.manterLogin = this.formLogin.value.manterLogin;
    if (!!this.manterLogin) {
      this.localStorage.setItem('manterLogin', true);
    } else {
      this.localStorage.removeStorage('manterLogin');
    }
  }
  fazerLogin() {
    if (this.formLogin.invalid) {
      return;
    }

    this.erroLogin = '';

    const body = {
      email:  this.formLogin.value.email,
      password: this.formLogin.value.senha
    };

    this.carregando = true;

    this.loginService.login(body).subscribe({
      next: (response: LoginInterface) => {
        this.carregando = false;
        if (response && response.token) {
          this.cookieService.setCookie('tokenLogin', response.token, 7);

          //monta objeto para salvar no localStorage
          const user = {
            name: response.name,
            email: response.email,
            userRoot: response.userRoot ? true : false,
          };
          this.localStorage.setItem('user', user);

          this.router.navigate(['/home']);
        } else {
          this.erroLogin = 'Resposta inválida do servidor.';
        }
      },
      error: (err) => {
        this.carregando = false;

        this.erroLogin = err.error.message ;
      }
    });
  }
}

<div class="min-h-screen  flex items-center justify-center p-4">
  <div class="max-w-md w-full bg-white rounded-xl shadow-lg p-8 border-2 " [ngClass]="erroLogin ? 'border-red-500' : 'border-gray-200'">
    <img src="assets/image/logo.png" alt="Fiscalize Finanças" class="w-40 h-40 mb-3 mx-auto">
    <h2 class="text-2xl font-bold text-gray-900 mb-6 text-center">Acesse sua conta    </h2>
 <!-- <div role="alert" class="mb-4 relative flex w-full p-3 text-sm text-white bg-sky-500 rounded-md">
    An success alert for showing message.
    <button class="flex items-center justify-center transition-all w-8 h-8 rounded-md text-white hover:bg-white/10 active:bg-white/10 absolute top-1.5 right-1.5" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-5 w-5" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path></svg>
    </button>
  </div> -->
        @if(erroLogin.length > 0) {
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-4 mb-4"

      role="alert">

  <span class="block sm:inline font-bold"> {{ erroLogin }}</span>
  <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
    <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
  </span>

</div>


    }
    <form [formGroup]="formLogin" (ngSubmit)="fazerLogin()" class="space-y-4" autocomplete="off">
      <div>
        <label class="block text-sm font-medium mb-1" for="email">E-mail</label>
        <input
          formControlName="email"
          type="email"
          name="email"
          autocomplete="none"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-sky-200 focus:border-sky-200 outline-none transition-all"
          placeholder="exemplo@email.com"
        />

      </div>

      <div>
        <label class="block text-sm font-medium mb-1">Senha</label>
        <input
          formControlName="senha"
          name="senha"
          type="password"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-sky-200 focus:border-sky-200 outline-none transition-all"
          placeholder="••••••••"
        />
      </div>

      <div class="flex items-center justify-between">
        <label class="flex items-center">
          <input type="checkbox" class="rounded border-gray-300 text-sky-600  focus:ring-sky-500 " formControlName="manterLogin" id="remember-me" (change)="salvaLogin()"/>
          <span class="ml-2 text-sm text-gray-600" for="remember-me">Manter acesso</span>
        </label>
        <a href="#" class="text-sm text-sky-600 hover:text-sky-700">Esqueci a senha</a>
      </div>

      <button
        [ngClass]="formLogin.invalid ? 'bg-gray-300 cursor-not-allowed' : 'bg-sky-500 hover:bg-sky-600'"
        [disabled]="formLogin.invalid"
        type="submit"
        class="w-full text-white font-medium py-2.5 rounded-lg transition-colors mt-4">

        {{ !!carregando ? '' : 'Entrar' }}
      </button>

    </form>


    <div class="mt-6 text-center text-sm text-gray-600">
      <a [routerLink]="['/cadastro']" class="text-sky-600 hover:text-sky-700 font-medium">Criar conta</a>
    </div>
  </div>
</div>
